*** Variables ***
${Browser}    chrome
${URL}    https://landmark.taqtics.co
${username}    intern@taqtics.co
${password}    TestIntern@123
${Invalid_username}   Intern@taqtics.co
${Invalid_password}     TestI@123
${Valid_username}    intern@taqtics.co
${Valid_password}    TestIntern@123

################ API Test Data############

${BASE_URL}    https://landmark.taqtics.co
${ADMIN_USER}    intern@taqtics.co
${ADMIN_PASS}    TestIntern@123
${NON_ADMIN_USER}    intern@taqtics.co
${NON_ADMIN_PASS}    nonAdminPass
${EMPTY}